version: "3.8"

services:
  
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  server:
    image: luna-container
    restart: always
    ports:
      - 7220:7220
    deploy:
      resources:
        limits:
          cpus: ".85"
          memory: 7200M
        reservations:
          cpus: '.05'
          memory: 800M
  
networks:
  default:
    driver: overlay
