<OutlinedLabel>:

    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Line:
            rectangle: (root.width * 0.6, root.height * 2.0, root.width * 4.8, root.height * 5.3)
            width: 1.1
            cap: 'round'
            joint: 'round'
    
OutlinedLabel:
    theme_text_color: 'Secondary'
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    size_hint: (None, None)
